language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: dzearing@hotmail.com
  api_key:
    secure: ZzFJnQoNyWq2IXcqxfTplmZeBfkZPmxQrBZHCjv0xLJJGtY9h39ap9hvDlw39NUiL5phIBfdBLpqX97Lroynvg4SlgCI197izGadx0ZHDr0OcGWqv/WL+jaDZpbUSjo2obTT3NU3Q92r/V9DI+lByDSx52N5SaS6LOf0FXXTFj08PEXK0HPLK66TKpM2UCaulEy07HTlVsmzRL7PPPySs/2016OefC+hAyKSpUARZcdGkrcJwbZJBVSNRZkAVp6Iz0DjGgY5X0GsF8mrekaHjl3jCgJPmVuco5nztINk79FsfZ/Pyel346uFUQdlisH0D1nJ947w47UzTVJ9HM0u93IpOAWA3UetmIzBuQGbKSc/F+P9BdMibRqG7ld3U672Rx2w2yV4lM/PUZMj2ip1OwUyO1d/q0oj2LmE++lROb+jxp4B0EMQ91r3g7JNRcS/e7l/glFvo0uKHL30XwRuzpj1ud4tWw4Iw715zWHt419+EmEKVDy6djBMYROOu4xE3nUGwRelNUyz47oy0YUrAeFEDKCTSb31q6fHHxHc6Z5532/Rp6PgmhhSAwibLcBVExb8+zOUGykX+nxNLTTAu6wb0VpoO/XwqyCK2jXiuzV/9Ju6VsF3Ish3LUHai6wt74mYdZqxwfQCKdyvmir9HfoBQR40lJH5ovBGiQpjVHI=
  on:
    tags: true
    repo: dzearing/gulp-core-build-typescript
