parameters:
  - name: BuildParameters
    type: string
    default: ''

steps:
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'

  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'

  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'

  # - bash: |
  #     /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  #     echo ">>> Started xvfb"
  #   displayName: Start xvfb
  #   condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - script: 'node common/scripts/install-run-rush.js retest --verbose --production ${{ parameters.BuildParameters }}'
    displayName: 'Rush retest (install-run-rush)'

  - script: |
      node apps/rush/lib/start-dev.js build --to rush-package-manager-integration-test
      cd build-tests/rush-package-manager-integration-test
      npm run test
    displayName: 'Run package manager integration tests'
