parameters:
  - name: BuildParameters
    type: string
    default: ''
  - name: PerformValidation
    type: boolean
    default: true

steps:
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'

  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'

  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'

  # - bash: |
  #     /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  #     echo ">>> Started xvfb"
  #   displayName: Start xvfb
  #   condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - script: 'node common/scripts/install-run-rush.js retest --verbose --production ${{ parameters.BuildParameters }}'
    displayName: 'Rush retest (install-run-rush)'

  - ${{ if eq(parameters.PerformValidation, true) }}:
      - script: 'node apps/rush/lib/start-dev.js test --verbose --production --timeline ${{ parameters.BuildParameters }}'
        displayName: 'Rush test (rush-lib)'

      - script: 'node repo-scripts/repo-toolbox/lib/start.js readme --verify'
        displayName: 'Ensure repo README is up-to-date'
