steps:
  - script: 'node repo-scripts/repo-toolbox/lib-commonjs/start.js record-versions --out-file $(Build.ArtifactStagingDirectory)/published-versions/published-versions.json'
    displayName: 'Record Published Versions'
  - script: 'node repo-scripts/repo-toolbox/lib-commonjs/start.js collect-project-files --subfolder temp/json-schemas --output-path $(Build.ArtifactStagingDirectory)/json-schemas'
    displayName: 'Collect JSON Schemas'
  - script: 'node repo-scripts/repo-toolbox/lib-commonjs/start.js collect-project-files --subfolder temp/api --output-path $(Build.ArtifactStagingDirectory)/api'
    displayName: 'Collect API review files'
